server:
  port: 8088
  tomcat:
        uri-encoding: UTF-8
        max-threads: 8000
        #最小备用线程数
        min-spare-threads: 800
  compression:
    enabled: true
  connection-timeout: 3000
xxl: 
  job:
    admin:
      addresses: http://192.168.1.131:8080/jobs/
    executor:
      ip: 
      port: 9999
      logpath: 
    accessToken: 
lock: 
  zookeeper-url: 120.77.69.63
  redis-url: 
thread: 
    coreSize: 800
    maxSize: 1000
    keepAliveTime: 100
spring:
    datasource:
        url: jdbc:mysql://192.168.1.9:3308/fare?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
    dubbo:   
        registry:   
            address: zookeeper://120.77.69.63:2181  
    redis: 
      url: 119.23.126.247
      port: 6379
      password: bdff85a964b4123901a292d3fbaa5483