#用于单独部署搜索  搜索 端口 8088 dubbo 服务接口 20880
server:
  tomcat:
    max-threads: 2000 #///最大线程数
    min-spare-threads:  2000 #初始化时创建的线程数
    accept-count: 2000 #允许的最大连接数，应大于等于maxProcessors，默认值为100
  port: 8088
  compression:
    enabled: true
  connection-timeout: 22000
xxl: 
  job:
    hold: false  #true 打开定时器  false 关闭定时器
    admin:
      addresses: http://119.23.131.196:8090/jobs/
    executor:
      ip: 
      port: 9998
      logpath: 
    accessToken: 
restrict:
      day: 6  #// 航线限制天数  包含
lock: 
  zookeeper-url: 120.77.69.63
  redis-url: 
hz:
  BackfillUrl: http://hzop.24-a.com:9099/hzop/backfillHzb/Backfill.do
  UpdateOrderUrl:  http://hzop.24-a.com:9099/hzop/backfillHzb/updateOrderStatus.do
thread: 
    coreSize: 80
    maxSize: 100
    queueCapacity: 200
    keepAliveTime: 5 #3 s 回收空闲线程
scheme:
   thread:
       cardinal: 5  #// x条报价一个线程  
       total: 6 #// 总报价数达到多少开启线程
spring:
    datasource:
        url: jdbc:mysql://119.23.131.196:3308/fare?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
        username: root
        password: root
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 6000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
    dubbo:   
        registry:   
            address: zookeeper://120.77.69.63:2181  
        #暴露服务方式  
        protocol:  
          #暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复）   
          port: 20881
    jodis: 
        url: 120.77.69.63:2181
        timeout: 30000
        zk: /jodis/codis-cache
        password: 123456
        db: 0
    redis: 
      url: r-wz9da8c1f4d4a544.redis.rds.aliyuncs.com
      port: 6379
      password: Hz**redis--2018
      database: 0