#用于单独部署搜索  搜索 端口 8088 dubbo 服务接口 20880
server:
  tomcat:
    max-threads: 800 #///最大线程数
    min-spare-threads:  400 #初始化时创建的线程数
    accept-count: 2000 #允许的最大连接数，应大于等于maxProcessors，默认值为100
  port: 8088
  compression:
    enabled: true
  connection-timeout: 2000

xxl: 
  job:
    hold: false  # false 关闭定时qi
    admin:
      addresses: http://192.168.1.9:8080/xxl-job-admin/
    executor:
      ip: 
      port: 9999
      logpath: 
    accessToken: 
lock: 
  zookeeper-url: 120.77.69.63
  redis-url: 
scheme:
   thread:
       cardinal: 1  #// x条报价一个线程  
       total: 2 #// 总报价数达到多少开启线程
restrict:
      day: 6  #// 航线限制天数  包含
thread: 
    coreSize: 500
    maxSize: 800
    keepAliveTime: 2 #3 s 回收空闲线程
    queueCapacity: 1000
spring:
    datasource:
        url: jdbc:mysql://daikuanniao.mysql.rds.aliyuncs.com:3306/phiz?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: Chengxu1990
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
    dubbo:   
        registry:   
            address: zookeeper://120.77.69.63:2181  
    redis: 
      url: 127.0.0.1
      port: 6379
      password: 
      database: 0